export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_REQUEST_ORIGIN: 'INVALID_REQUEST_ORIGIN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NOT_CONNECTED_GITHUB_YET: 'NOT_CONNECTED_GITHUB_YET',
  CANNOT_GET_LIST_REPOS_FROM_GITHUB: 'CANNOT_GET_LIST_REPOS_FROM_GITHUB',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
