// Error codes from backend
export const ERROR_CODES = {
  P2003: 'P2003',
  P2002: 'P2002',
  P2025: 'P2025',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZE: 'UNAUTHORIZE',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_QUERY_STRUCTURE: 'INVALID_QUERY_STRUCTURE',
  REQUIRE_LOGIN: 'REQUIRE_LOGIN',
  ACCOUNT_IS_LOCKED: 'ACCOUNT_IS_LOCKED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  MAX_DEVICE_REACHED: 'MAX_DEVICE_REACHED',
  DUPLICATE_USER_EMAIL: 'DUPLICATE_USER_EMAIL',
  INVALID_TOKEN: 'INVALID_TOKEN',
  DUPLICATE_FOLDER_NAME: 'DUPLICATE_FOLDER_NAME',
  DUPLICATE_DATASET_NAME: 'DUPLICATE_DATASET_NAME',
  ALREADY_CHECKIN: 'ALREADY_CHECKIN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
